#!/bin/bash

#Call downloader.sh with the right parameter
#./downloader.sh europe albania
#./downloader.sh europe alps
#./downloader.sh europe andorra
#./downloader.sh europe austria
#./downloader.sh europe azores
#./downloader.sh europe belarus
#./downloader.sh europe belgium
#./downloader.sh europe bosnia-herzegovina
#./downloader.sh europe british_isles
#./downloader.sh europe bulgaria
#./downloader.sh europe croatia
#./downloader.sh europe cyprus
#./downloader.sh europe czech_republic
#./downloader.sh europe denmark
#./downloader.sh europe estonia
#./downloader.sh europe faroe_islands
#./downloader.sh europe finland
#./downloader.sh europe france
#./downloader.sh europe germany
#./downloader.sh europe great_britain
#./downloader.sh europe greece
#./downloader.sh europe hungary
#./downloader.sh europe iceland
#./downloader.sh europe ireland
#./downloader.sh europe isle_of_man
./downloader.sh europe italy
#./downloader.sh europe kosovo
#./downloader.sh europe latvia
#./downloader.sh europe liechtenstein
#./downloader.sh europe lithuania
#./downloader.sh europe luxembourg
#./downloader.sh europe macedonia
#./downloader.sh europe malta
#./downloader.sh europe moldova
#./downloader.sh europe monaco
#./downloader.sh europe montenegro
#./downloader.sh europe netherlands
#./downloader.sh europe norway
#./downloader.sh europe poland
#./downloader.sh europe portugal
#./downloader.sh europe romania
#./downloader.sh europe serbia
#./downloader.sh europe slovakia
#./downloader.sh europe slovenia
#./downloader.sh europe spain
#./downloader.sh europe sweden
#./downloader.sh europe switzerland
#./downloader.sh europe turkey
#./downloader.sh europe ukraine
